# Generated by Django 6.0.6 on 2026-06-28 15:37

import django_ckeditor_5.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(blank=True, help_text='Enter the title in Kyrgyz language', max_length=255, null=True, verbose_name='Title in Kyrgyz')),
                ('title_ru', models.CharField(blank=True, help_text='Enter the title in Russian language', max_length=255, null=True, verbose_name='Title in Russian')),
                ('title_en', models.CharField(blank=True, help_text='Enter the title in English language', max_length=255, null=True, verbose_name='Title in English')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created date')),
                ('status', models.BooleanField(default=True, help_text='Show status', verbose_name='Status')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='link')),
                ('url', models.CharField(blank=True, null=True, verbose_name='model url')),
                ('page_slug', models.CharField(blank=True, null=True, verbose_name='model slug')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created date')),
                ('status', models.BooleanField(default=True, help_text='Show status', verbose_name='Status')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'A pointer to a page',
                'verbose_name_plural': 'A pointer to a page',
            },
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.mainmodel')),
                ('content_kg', django_ckeditor_5.fields.CKEditor5Field(blank=True, config_name='extends', help_text='Enter the content in Kyrgyz language', null=True, verbose_name='Content in Kyrgyz')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, config_name='extends', help_text='Enter the content in Russian language', null=True, verbose_name='Content in Russian')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, config_name='extends', help_text='Enter the content in English language', null=True, verbose_name='Content in English')),
            ],
            bases=('core.mainmodel',),
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.mainmodel')),
                ('order', models.PositiveIntegerField(blank=True, default=1, help_text='Show the order', null=True, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Main menu',
                'verbose_name_plural': 'Main menu',
                'ordering': ('order', 'id'),
            },
            bases=('core.mainmodel',),
        ),
        migrations.CreateModel(
            name='MainMenuLinks',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.mainmodel')),
                ('order', models.PositiveIntegerField(blank=True, default=1, help_text='Show the order', null=True, verbose_name='Order')),
                ('on_footer_menu', models.BooleanField(blank=True, default=False, help_text='Display from the footer section', null=True, verbose_name='Footer menu')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_link_to', to='core.pageurls', verbose_name='Link of page')),
                ('main_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='core.mainmenu', verbose_name='Main menu')),
            ],
            options={
                'verbose_name': 'Main module',
                'verbose_name_plural': 'Main module',
                'ordering': ('order', 'id'),
            },
            bases=('core.mainmodel',),
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('page_url', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pageurls')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=('core.basemodel',),
        ),
    ]
