# Generated by Django 6.0.6 on 2026-06-29 15:28

import core.models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(blank=True, help_text='Введите название на кыргызском языке', max_length=255, null=True, verbose_name='Название на кыргызском')),
                ('title_ru', models.CharField(blank=True, help_text='Введите название на русском языке', max_length=255, null=True, verbose_name='Название на русском')),
                ('title_en', models.CharField(blank=True, help_text='Введите название на английском языке', max_length=255, null=True, verbose_name='Название на английском')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('status', models.BooleanField(default=True, help_text='Показать статус', verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('content_kg', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите контент на кыргызском языке', null=True, verbose_name='Контент на кыргызском')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите контент на русском языке', null=True, verbose_name='Контент на русском')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите контент на английском языке', null=True, verbose_name='Контент на английском')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
            ],
            options={
                'verbose_name': 'О клинике',
                'verbose_name_plural': 'О клинике',
                'ordering': ('id', 'created'),
            },
            bases=('core.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created',),
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузить изображение', upload_to=core.models.get_upload_name, verbose_name='Изображение')),
                ('main_image', models.BooleanField(default=False, help_text='Основное изображение')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.news', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Фотографии новостей',
                'verbose_name_plural': 'Фотографии новостей',
                'ordering': ('-created',),
            },
        ),
    ]
