# Generated by Django 6.0.6 on 2026-06-28 16:37

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Главное меню', 'verbose_name_plural': 'Главное меню'},
        ),
        migrations.AlterModelOptions(
            name='mainmenulinks',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Главный модуль', 'verbose_name_plural': 'Главные модули'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='pageurls',
            options={'verbose_name': 'Указатель на страницу', 'verbose_name_plural': 'Указатели на страницу'},
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите контент на английском языке', null=True, verbose_name='Контент на английском'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='content_kg',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите контент на кыргызском языке', null=True, verbose_name='Контент на кыргызском'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите контент на русском языке', null=True, verbose_name='Контент на русском'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Показать порядок', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='mainmenulinks',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_link_to', to='core.pageurls', verbose_name='Ссылка на страницу'),
        ),
        migrations.AlterField(
            model_name='mainmenulinks',
            name='main_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='core.mainmenu', verbose_name='Главное меню'),
        ),
        migrations.AlterField(
            model_name='mainmenulinks',
            name='on_footer_menu',
            field=models.BooleanField(blank=True, default=False, help_text='Отображать в футере', null=True, verbose_name='Меню футера'),
        ),
        migrations.AlterField(
            model_name='mainmenulinks',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Показать порядок', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='status',
            field=models.BooleanField(default=True, help_text='Показать статус', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='title_en',
            field=models.CharField(blank=True, help_text='Введите название на английском языке', max_length=255, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='title_kg',
            field=models.CharField(blank=True, help_text='Введите название на кыргызском языке', max_length=255, null=True, verbose_name='Название на кыргызском'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Введите название на русском языке', max_length=255, null=True, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='pageurls',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pageurls',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='pageurls',
            name='page_slug',
            field=models.CharField(blank=True, null=True, verbose_name='slug модели'),
        ),
        migrations.AlterField(
            model_name='pageurls',
            name='status',
            field=models.BooleanField(default=True, help_text='Показать статус', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pageurls',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='url модели'),
        ),
    ]
