# Generated by Django 6.0.6 on 2026-06-29 17:38

import core.models
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО на кыргызском')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО на русском')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО на английском')),
                ('job_title_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность на кыргызском')),
                ('job_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность на русском')),
                ('job_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность на английском')),
                ('content_kg', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите характеристику на кыргызском языке', null=True, verbose_name='Характеристика на кыргызском')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите характеристику на русском языке', null=True, verbose_name='Характеристика на русском')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите характеристику на английском языке', null=True, verbose_name='Характеристика на английском')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.get_upload_name_management, verbose_name='Изображение')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('status', models.BooleanField(default=True, help_text='Показать статус', verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('order', models.PositiveIntegerField(blank=True, default=1, help_text='Показать порядок', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководства',
                'ordering': ('order', 'id'),
            },
        ),
    ]
