# Generated by Django 6.0.6 on 2026-06-29 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на кыргызском')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на русском')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на английском')),
                ('department_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел на кыргызском')),
                ('department_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел на русском')),
                ('department_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел на английском')),
                ('schedule_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='График на кыргызском')),
                ('schedule_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='График на русском')),
                ('schedule_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='График на английском')),
                ('salary_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Зарплата на кыргызском')),
                ('salary_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Зарплата на русском')),
                ('salary_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Зарплата на английском')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='Список требований', verbose_name='Требования')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='Список обязанностей', verbose_name='Обязанности')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('status', models.BooleanField(default=True, help_text='Показать статус', verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('order', 'id'),
            },
        ),
    ]
