# Generated by Django 6.0.6 on 2026-06-28 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mainmenu_options_alter_mainmenulinks_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenulinks',
            name='main_menu',
        ),
        migrations.RemoveField(
            model_name='mainmenulinks',
            name='link',
        ),
        migrations.RemoveField(
            model_name='mainmenulinks',
            name='mainmodel_ptr',
        ),
        migrations.CreateModel(
            name='MenuLinks',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.mainmodel')),
                ('service_type', models.CharField(choices=[('menu', 'Меню'), ('link', 'Ссылка')], default='menu', help_text='Указать тип', verbose_name='Тип меню')),
                ('order', models.PositiveIntegerField(blank=True, default=1, help_text='Показать порядок', null=True, verbose_name='Порядок')),
                ('on_footer_menu', models.BooleanField(blank=True, default=False, help_text='Отображать в футере', null=True, verbose_name='Меню футера')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_link_to', to='core.pageurls', verbose_name='Ссылка на страницу')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='core.menulinks', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
                'ordering': ('order', 'id'),
            },
            bases=('core.mainmodel',),
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('page_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.pagecontent', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Дополнительная страница',
                'verbose_name_plural': 'Дополнительные страницы',
                'ordering': ('id', 'created'),
            },
            bases=('core.basemodel',),
        ),
        migrations.DeleteModel(
            name='MainMenu',
        ),
        migrations.DeleteModel(
            name='MainMenuLinks',
        ),
    ]
