# Generated by Django 6.0.6 on 2026-06-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, help_text='Требования через запятую', null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Обязанности через запятую', null=True, verbose_name='Обязанности'),
        ),
    ]
