# Generated by Django 6.0.6 on 2026-06-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vacancy_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='basemodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='management',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='management',
            name='job_title_en',
        ),
        migrations.RemoveField(
            model_name='management',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='department_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='schedule_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title_en',
        ),
    ]
