# Generated by Django 6.0.6 on 2026-06-30 11:06

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_basemodel_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на кыргызском')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском')),
                ('category', models.CharField(choices=[('polyclinic', 'Поликлиника'), ('stationary', 'Стационар'), ('ogpmu', 'ОГПМУ'), ('general', 'Общее')], default='general', max_length=50, verbose_name='Категория')),
                ('image', models.ImageField(help_text='Загрузить изображение', upload_to=core.models.get_upload_name_gallery, verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Порядок')),
                ('status', models.BooleanField(default=True, help_text='Показать статус', verbose_name='Статус')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фотография галереи',
                'verbose_name_plural': 'Фотографии галереи',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на кыргызском')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском')),
                ('description_kg', models.TextField(blank=True, null=True, verbose_name='Описание на кыргызском')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание на русском')),
                ('category', models.CharField(choices=[('polyclinic', 'Поликлиника'), ('stationary', 'Стационар'), ('ogpmu', 'ОГПМУ'), ('general', 'Общее')], default='general', max_length=50, verbose_name='Категория')),
                ('youtube_url', models.URLField(help_text='Вставьте ссылку на видео YouTube', max_length=500, verbose_name='YouTube URL')),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Порядок')),
                ('status', models.BooleanField(default=True, help_text='Показать статус', verbose_name='Статус')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Видео галереи',
                'verbose_name_plural': 'Видео галереи',
                'ordering': ('order', 'id'),
            },
        ),
    ]
