# Generated by Django 6.0.6 on 2026-06-30 11:45

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_galleryimage_videogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на кыргызском')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском')),
                ('category', models.CharField(choices=[('polyclinic', 'Поликлиника'), ('stationary', 'Стационар'), ('ogpmu', 'ОГПМУ'), ('general', 'Общее')], default='general', max_length=50, verbose_name='Категория')),
                ('status', models.BooleanField(default=True, help_text='Показать статус', verbose_name='Статус')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Альбом галереи',
                'verbose_name_plural': 'Альбомы галереи',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузить изображение', upload_to=core.models.get_upload_name_gallery, verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, help_text='Основное изображение')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.galleryalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография альбома',
                'verbose_name_plural': 'Фотографии альбома',
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'ordering': ('-created',), 'verbose_name': 'Видео галереи', 'verbose_name_plural': 'Видео галереи'},
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='order',
        ),
    ]
